import java.sql.*;


public class ModelDBQuery extends DBConnection {
	
  	private static ResultSet datenmenge;

 
  /**
   * 
   * @param Insert a new data in database.
   */
  	public static void insert (ModelPersonalData daten) 
    {
    	verbinden();
      try 
      {
        befehl.executeUpdate("insert into daten values ("+daten.getSchluessel()+", '"+daten.getname()+"', '"+daten.getvorname()+"', '"+daten.getStrasse()+"', "+daten.getHausnr()+", '"+daten.getOrt()+"',"+daten.getplz()+","+daten.getHandy()+")");
  	}    
  	catch (Exception ae) {ae.printStackTrace();}
      schliessen();}
  	
  	
  /**
   * 
   * @Returns the last id number
   */
  public static int getSchlüssel() 
  {
	    verbinden();
	    int puffer=0;
	    try 
	    {
	      ResultSet datenmenge;
	      datenmenge = befehl.executeQuery("SELECT max(IDnummer) from daten;");
	      datenmenge.next();
	      puffer = datenmenge.getInt(1);
	    }
	    catch (Exception ae) 
	    {
	      ae.printStackTrace();
	    }
	    schliessen();
	    return(puffer);
  }
  
  /**
   *  Selects all dates.
   */
  public static void StartAbfrage()
  {
	    verbinden();
	    try
	    {
	    	datenmenge = befehl.executeQuery("SELECT * from daten");
	    }
	      	
	    catch ( Exception ae) 
	    {
	      ae.printStackTrace();
	    }
	  }
/**
 * 
 * @returns the next data, the results generated by the query.
 */
  public static ModelPersonalData getNext() {
  
	    try 
	    {
	      int schluessel=0;
	      String name="";
	      String vorname="";
	      String Strasse="";
	      int hausnr=0;
	      String ort="";
	      int plz=0;
	      
	      long handy=0;

	
	      if(datenmenge.next())
	      {

	        schluessel= datenmenge.getInt("IDnummer");
	        name =  datenmenge.getString("Name").trim();
	        vorname =  datenmenge.getString("Vorname");
	        Strasse =  datenmenge.getString("Strasse");
	        hausnr=datenmenge.getInt("HausNr");
	        ort =  datenmenge.getString("Ort");
	        plz =  datenmenge.getInt("PLZ");
	        handy=datenmenge.getLong("Handy");

	        
	      //-erzeugt neues Exemplar daten, welches übergeben wird---------------------------------------*
	      return(new ModelPersonalData(schluessel, name,vorname,Strasse,hausnr,ort,plz,handy));
	      

	      
	      }
	      
	      else
	      {
	        return null;
	   	  }
	
	    }
	    catch (Exception ae) {
	      ae.printStackTrace();
	      return(null);
	    }
  }
  
  /**
   * 
   * @param makes an update of data with this key number.
   */
  public static boolean updatelöschen(int IDnummer)
  {
	  int x=IDnummer+1;
	  verbinden();
	    try 
	    {
	      befehl.executeUpdate( "UPDATE daten SET IDnummer = "+IDnummer+" WHERE IDnummer = "+x);
	      System.out.println(x+ " " + IDnummer + "oldu");
	      return true;
	    }
	    catch (Exception ae) 
	    {
	      ae.printStackTrace();
	      return false;
	    }
	   
  }
  /**
   * 
   * @param Makes an update in database
   */
  public static boolean update(ModelPersonalData daten)
  {
	  verbinden();
	    try 
	    {
	    	befehl.executeUpdate("UPDATE daten SET Name='"+daten.getname()+"' WHERE IDnummer="+daten.getSchluessel()+" ");
	        befehl.executeUpdate("UPDATE daten SET Vorname='"+daten.getvorname()+"' WHERE IDnummer="+daten.getSchluessel()+" ");
	        befehl.executeUpdate("UPDATE daten SET Strasse='"+daten.getStrasse()+"' WHERE IDnummer="+daten.getSchluessel()+" ");
	        befehl.executeUpdate("UPDATE daten SET HausNr="+daten.getHausnr()+" WHERE IDnummer="+daten.getSchluessel()+" ");
	        befehl.executeUpdate("UPDATE daten SET Ort='"+daten.getOrt()+"' WHERE IDnummer="+daten.getSchluessel()+" ");
	        befehl.executeUpdate("UPDATE daten SET PLZ="+daten.getplz()+" WHERE IDnummer="+daten.getSchluessel()+" ");
	        befehl.executeUpdate("UPDATE daten SET Handy="+daten.getHandy()+" WHERE IDnummer="+daten.getSchluessel()+" ");
	        return true;
	    }
	    catch (Exception ae) 
	    {
	      ae.printStackTrace();
		    return false;

	    }
  }
  
  /**
   * 
   * @param Deletes the date with this key number.
   */
  public static boolean delete (int schluessel) 
  {
	    verbinden();
	    try 
	    {
	      befehl.executeUpdate("delete from daten where IDnummer= "+schluessel);
	      System.out.println("delete from artikel where IDnummer= "+schluessel);
	      return true;
	    }
	    catch (Exception ae) 
	    {
	      ae.printStackTrace();
		  return false;

	    }
	    
  }
  
  /**
   * Deletes the all Table.
   */
  public static boolean deleteAll()
  {
	  verbinden();
	    try 
	    {
	      befehl.executeUpdate("drop table daten");
	      return true;
	    }
	    catch (Exception ae) 
	    {
	      ae.printStackTrace();
		    return false;

	    }
  }
  
  
}



